quarkus:
  application:
    name: grpc-locations
  banner:
    path: banner.txt
  log:
    level: INFO
    category:
      "io.quarkus.sample.superheroes":
        level: DEBUG
    console:
      level: INFO
      darken: 1
  http:
    port: 8089
    test-port: 0
  grpc:
    server:
      use-separate-server: false
      enable-reflection-service: true
      port: "${quarkus.http.port}"
      test-port: "${quarkus.http.test-port}"
  datasource:
    jdbc:
      telemetry: true
    devservices:
      image-name: mariadb:11.5
  otel:
    resource:
      attributes: "app=${quarkus.application.name},application=grpc-locations,system=quarkus-super-heroes"
    exporter:
      otlp:
        protocol: http/protobuf
    metrics:
      enabled: true
    logs:
      enabled: true
  hibernate-orm:
    schema-management:
      strategy: drop-and-create
  container-image:
    builder: docker
    registry: quay.io
    group: quarkus-super-heroes
    name: "${quarkus.application.name}"

"%dev,test":
  quarkus:
    log:
      console:
        level: DEBUG

"%test":
  quarkus:
    otel:
      sdk:
        disabled: true

"%prod":
  quarkus:
    hibernate-orm:
      sql-load-script: import.sql
