quarkus:
  application:
    name: rest-heroes
  banner:
    path: banner.txt
  log:
    level: INFO
    category:
      "io.quarkus.sample.superheroes":
        level: DEBUG
    console:
      level: INFO
      darken: 1
  otel:
    resource:
      attributes: "app=${quarkus.application.name},application=heroes-service,system=quarkus-super-heroes"
    exporter:
      otlp:
        protocol: http/protobuf
    metrics:
      enabled: true
    logs:
      enabled: true
  hibernate-orm:
    schema-management:
      strategy: drop-and-create
  http:
    port: 8083
    test-port: 0
  jackson:
    serialization-inclusion: non-empty
  rest:
    jackson:
      optimization:
        enable-reflection-free-serializers: true
  swagger-ui:
    always-include: true
  openapi:
    generator:
      server:
        spec: openapi.yml
        base-package: io.quarkus.sample.superheroes.hero.api
        use: openapitools
        use-bean-validation: true
        use-builder: true
        use-reactive: true
  container-image:
    builder: docker
    registry: quay.io
    group: quarkus-super-heroes
    name: "${quarkus.application.name}"

"%dev,test":
  quarkus:
    log:
      console:
        level: DEBUG

"%test":
  quarkus:
    otel:
      sdk:
        disabled: true

"%prod":
  quarkus:
    hibernate-orm:
      sql-load-script: import.sql
