quarkus.application.name=rest-villains
quarkus.banner.path=banner.txt

## HTTP configuration
quarkus.http.port=8084
quarkus.http.test-port=0
quarkus.jackson.serialization-inclusion=non-empty
quarkus.rest.jackson.optimization.enable-reflection-free-serializers=true

# drop and create the database at startup (use `update` to only update the schema or 'validate' to only validate the schema)
quarkus.hibernate-orm.schema-management.strategy=drop-and-create

# Villain service specific properties (see io.quarkus.sample.superheroes.villain.config.VillainConfig)
villain.level.multiplier=0.5
%test.villain.level.multiplier=1

## Logging configuration
quarkus.log.category."io.quarkus.sample.superheroes".level=DEBUG
quarkus.log.level=INFO
quarkus.log.console.level=INFO
quarkus.log.console.darken=1
%dev,test.quarkus.log.console.level=DEBUG

# OpenTelemetry
quarkus.otel.resource.attributes=app=${quarkus.application.name},application=villains-service,system=quarkus-super-heroes
quarkus.otel.exporter.otlp.protocol=http/protobuf
quarkus.otel.metrics.enabled=true
quarkus.otel.logs.enabled=true
%test.quarkus.otel.sdk.disabled=true
quarkus.datasource.jdbc.telemetry=true

# prod configuration
%prod.quarkus.hibernate-orm.sql-load-script=import.sql

# OpenAPI
quarkus.swagger-ui.always-include=true

# OpenAPI Generator Server (contract-first)
quarkus.openapi.generator.server.spec=openapi.yml
quarkus.openapi.generator.server.base-package=io.quarkus.sample.superheroes.villain.api
quarkus.openapi.generator.server.use=openapitools
quarkus.openapi.generator.server.use-bean-validation=true
quarkus.openapi.generator.server.use-builder=true

# Container image
quarkus.container-image.builder=docker
quarkus.container-image.registry=quay.io
quarkus.container-image.group=quarkus-super-heroes
quarkus.container-image.name=${quarkus.application.name}
